version: '3.9'
name: webapi
services:
  webapi:
    build:
      context: .
    env_file:
        - .env
    image: webapi
    container_name: webapi
    working_dir: ${PATH_API}
    restart: on-failure
    environment:
      NODE_ENV: production
      TZ: America/Sao_Paulo
    network_mode: "host"
    logging:
        options:
            max-size: 8m
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
